### ISSUE TITLE
Firefox v.35 is freezing with the new version

### ISSUE THREAD

**Issue by geraldobh** [inbasic/ignotifier#285] opened 2015-01-15 12:55 UTC
New computer, fresh install of Firefox v.35, fresh install of Gmail Notifier 0.5.1.
Firefox is freezing
Do not supprt more than one account

**Comment by LocutusX** [comment] 2015-01-16 03:23
I have also started having issues with this plugin (v0.5.1) in Firefox 35, but they involve the OPTIONS button and the MORE hyperlink in the Firefox Add-Ons Manager. If either of those UI elements are clicked, **Firefox will completely hang (freeze)**. You cannot continue to use the application at that point; you must use your OS to close the process and re-start it.

Reproduced on two separate installs of Firefox 35; one was running Windows 7 SP1, the other was running Windows 8.1.

**Comment by geraldobh** [comment] 2015-01-16 11:53
Totally agree.  I could simutate this issue too.

**Comment by JohnnyGaloshes** [comment] 2015-01-29 19:56
I am having same issue. If you click the Options button it freezes all windows and you can't click anything. Also i cannot add more than the primary account.

**Comment by inbasic** [comment] 2015-01-31 12:52
Okay, can you guys try these steps and let me know what is the outcome?

1. Open `resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/ignotifier/data/options/index.html` in a browser tab

2. Open `chrome://ignotifier/content/options-opener.xul` in a new tab

Please make sure you have the latest version installed.

**Comment by JohnnyGaloshes** [comment] 2015-01-31 14:24
If i use

resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/ignotifier/data/options/index.html

it will open the Gmail Notifier options.

**Comment by Bearborg** [comment] 2015-01-31 17:01
As JohnnyGaloshes said, the resource:// link opens the options without a hitch. However, the chrome:// link gives me "file not found".

**Comment by inbasic** [comment] 2015-02-04 13:18
Is this fixed on 0.5.2b1?
https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/versions

**Closed** 2015-02-09 08:05 UTC

**Comment by Bearborg** [comment] 2015-02-09 12:25
I'm still experiencing this issue on 0.5.2.

**Comment by inbasic** [comment] 2015-02-09 12:33
@Bearborg so on version 0.5.2 when you click on the "Preferences" button in the addon manager, still Firefox freezes?

**Comment by Bearborg** [comment] 2015-02-09 12:35
If you mean "Options", yes, that's what happens.

**Comment by inbasic** [comment] 2015-02-09 12:41
okay then, open Error Console first (Ctrl + Shift + J), then click on the "Options" one more time. Wait for a few seconds and see if there is a new log/error in the Console. If so let me know what is the log.

Btw, in my case the button label is "Preferences",
![screen shot 2015-02-09 at 16 09 35](https://cloud.githubusercontent.com/assets/351062/6106375/1ddfde94-b076-11e4-8a20-834300a30eeb.png)
Maybe because I am on Mac.

**Comment by Bearborg** [comment] 2015-02-09 12:44
No new messages popped up in the Error Console.

**Comment by inbasic** [comment] 2015-02-09 12:46
That's weird! 
Can you open options, from this link `chrome://ignotifier/content/options-opener.xul`?

**Comment by Bearborg** [comment] 2015-02-09 12:46
"Firefox can't find the file at chrome://ignotifier/content/options-opener.xul."

**Comment by inbasic** [comment] 2015-02-09 12:53
I see. How about version 0.5.2.1?
https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/versions/

**Comment by Bearborg** [comment] 2015-02-09 12:55
Awesome, that fixed it!

**Comment by inbasic** [comment] 2015-02-09 12:56
Great!
