### ISSUE TITLE
Second account not working

### ISSUE THREAD

**Issue by Flema** [inbasic/ignotifier#298] opened 2015-02-25 08:19 UTC
Hi,

I have a problem with the notifier. I have two accounts but  I only want notifications on my second one, so I left empty the field on /mail/u/0/ and I put the inbox label on /mail/u/1/. 

Before the last two updates or so of the addon, this configuration worked pretty well. But now, the addon only shows notifications of /mail/u/0/ even though I don't have any label on its field and completely ignores the inbox label on my /mail/u/1/. 

Can you help me? 

Thank you.

**Comment by inbasic** [comment] 2015-02-26 10:55
Can you share an screenshot of the feeds section?

**Comment by KissDaniGH** [comment] 2015-02-26 18:39
without "inbox" neweset version recognizes only the first/primary account.
if u option/gmail Primary account (/mail/u/0/) and Secondary account (/mail/u/1/) put "inbox" gmail restartless recognizes all the 2 accounts.

**Comment by iSnipeu** [comment] 2015-03-13 10:26
> if u option/gmail Primary account (/mail/u/0/) and Secondary account (/mail/u/1/) put "inbox" gmail restartless recognizes all the 2 accounts.
This worked for me, thanks!

**Comment by Flema** [comment] 2015-03-13 22:52
Sorry, I was unable to answer sooner. 

If I have my settings like these:
![settings2](https://cloud.githubusercontent.com/assets/11189586/6648526/f6db72d0-c9da-11e4-903a-a6aeaac4b7e5.jpg)
the addon only shows notifications of /mail/u/0 and I don't want the notifications for that account, I just want the notifications for my secondary account.

The only solution I found is to log in in my secondary account first  so it becomes my primary account and, frankly, it's a bit of an inconvenience.

**Comment by inbasic** [comment] 2015-03-14 15:20
Is this fixed on the latest beta version (0.5.3b3)?
https://addons.mozilla.org/firefox/downloads/file/303658/gmail_notifier_restartless-0.5.3b3-fx.xpi?src=devhub

**Comment by Flema** [comment] 2015-03-21 17:04
I tried installing that version but it doesn't work. Thank you anyway for trying to solve this issue, hope it works in the end.

**Comment by lililya** [comment] 2015-03-22 16:23
Thanks

**Comment by inbasic** [comment] 2015-03-26 11:10
@Flema please try the latest beta again, https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/versions/

I am pretty sure the issue is fixed now.

**Comment by KissDaniGH** [comment] 2015-03-26 11:39
no luck here :(
seems still not ok

**Comment by KissDaniGH** [comment] 2015-03-26 11:40
sorry it was too fast. 
ok 4 me, thanks

**Comment by Flema** [comment] 2015-03-26 22:59
Yay! It works!! Thank you so much for your patience and for solving this problem. Very appreciated.

**Comment by inbasic** [comment] 2015-03-27 09:41
Perfect!

**Closed by inbasic** 2015-03-27 09:41 UTC
