### ISSUE TITLE
Mark all as Read button gone?

### ISSUE THREAD

**Issue by WybeBosch** [inbasic/ignotifier#572] opened 2021-05-29 08:35 UTC
Hey there, 
After having used this extension for years i am sad to see that the "mark all as read" button is gone. 
Is this intended? or is this a bug that perhaps can be fixed? 

Since i have used the extension for years, i find myself clicking in the exact spot where it used to be..

**Comment by br4nch** [comment] 2021-05-30 04:49
Might be a duplicate of #571. I checked version 0.9.9 but the button still not displayed @inbasic 
![image](https://user-images.githubusercontent.com/20967549/120092429-e939a600-c13c-11eb-848f-2336b149e019.png)
![image](https://user-images.githubusercontent.com/20967549/120092440-fb1b4900-c13c-11eb-8cad-f1f04559e90d.png)

**Comment by inbasic** [comment] 2021-05-30 05:12
Do you have the latest release? What is your browser? OS?

**Comment by br4nch** [comment] 2021-05-30 05:19
Here are some information
![image](https://user-images.githubusercontent.com/20967549/120092924-c90be600-c140-11eb-9725-8a8bb5f8e8bc.png)
![image](https://user-images.githubusercontent.com/20967549/120092983-4172a700-c141-11eb-92c7-6fda7943e4b7.png)

**Closed** 2021-05-30 05:35 UTC

**Comment by inbasic** [comment] 2021-05-30 05:38
thanks for the report. Will be fixed by 1.0.0 release.
