### ISSUE TITLE
Lost Sound

### ISSUE THREAD

**Issue by trocoms** [inbasic/ignotifier#354] opened 2015-09-22 15:55 UTC
Sound Notification does not work in Gmail Notifier (Restartless) 0.5.7.2 in Firefox 40.0.3

**Comment by Victoria54321** [comment] 2015-09-24 16:25
Having the same problem.  It just stopped working, perhaps with update to Firefox 41.  When I browse and select the .wav file to play, it doesn't stay in the settings, but reverts to "No file selected"

**Comment by ripplesync** [comment] 2015-09-25 11:56
I'm experiencing the same issue after I updated to FF41. Tried with both *.mp3 and *.wav, but there is no sound. I can confirm that it reverts to "No file selected".

**Comment by murph57** [comment] 2015-09-25 23:44
Same problem. I did notice that I can get a sound, if I chose one of the four other options, other than "User defined", but I prefer a longer more distinct sound.

**Comment by Taurean75** [comment] 2015-09-27 00:30
I believe it's broken in Firefox 41. It stopped working ever since I upgraded to v41.

**Comment by retardTonic** [comment] 2015-09-29 10:31
My addon which uses the same mechanism was affected as well. The log says "Security Error: Content at ... may not load or link to resource ...".

**Comment by inbasic** [comment] 2015-10-04 08:09
Is this fixed on the latest dev version?
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true

Download the XPI and drop it into your Firefox browser

**Comment by Imold** [comment] 2015-10-04 22:41
I just tested the dev version and there's still no sound. I think fire fox 41 broke something with the restartless add ons, because I'm having the same problem with "Feedly Notifier" but not not with "Download Manager (S3)".

**Comment by Taurean75** [comment] 2015-10-05 00:10
I just reinstalled it after re-packaging it with the sound file I want.

**Comment by inbasic** [comment] 2015-10-05 07:28
@Imold do you still get the `Security Error: Content at ... may not load or link to resource ...` error in the console? Are you sure you are on the latest dev? If so try the notifier on a clean profile, https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

@Taurean75 try the latest dev

**Comment by Imold** [comment] 2015-10-05 16:19
Can you tell me where I am supposed to be getting Security Error: Content at ... may not load or link to resource ...? So that I can tell you if I am.

**Comment by inbasic** [comment] 2015-10-06 05:58
Open the error console (Ctrl + Shift + J), clear it. Now middle click on the toolbar button to force sound notification.

**Comment by trocoms** [comment] 2015-10-06 14:43
did not work

**Comment by Imold** [comment] 2015-10-06 16:32
I don't seem to be getting it.

**Comment by Imold** [comment] 2015-10-06 19:13
I found the problem. Go to about:config and find media.autoplay.enabled if it is set to false then change it to true. This fixed it for me.

**Comment by trocoms** [comment] 2015-10-06 19:17
did not work for me

**Comment by inbasic** [comment] 2015-10-07 06:32
@Imold you have disabled the pref manually right?

@trocoms can you open "resource://igsound/" in a browser tab when the latest dev is installed? You need to manually fire the notification once to let the extension prepare the url. Just middle click on the toolbar button once you have a badge number.

**Comment by Imold** [comment] 2015-10-07 21:50
Right I just set it to true and that got it working. Also make sure you're using the latest dev version. I don't know if it will work if you're not.

**Comment by Victoria54321** [comment] 2015-10-16 22:36
It's working again!  I didn't change anything except an update to Firefox today, and now my user defined sound is working.  Yay!

**Comment by simonbcn** [comment] 2015-10-22 09:56
Ok, I had the same problem but I've changed the pref `media.autoplay.enabled` to true and now it's working again. :+1:

**Comment by Taurean75** [comment] 2015-11-10 20:57
It's broken again in v42.

**Closed** 2015-12-06 09:21 UTC
