### ISSUE TITLE
0.6.2 Not Working with Chrome Either I GIVE UP

### ISSUE THREAD

**Issue by bob603** [inbasic/ignotifier#390] opened 2016-02-23 21:05 UTC
After using this for a couple of years now, I'm about to give up. I tried setting up in Chrome too after being told there is nothing wrong with this version, and I cannot get it to work with that browser either. It refused to remember GM account and passwords no matter what I do: create new profile, use different browser altogether, whatever.

**Comment by inbasic** [comment] 2016-02-27 11:01
In Chrome debugging is simpler. Open chrome://extensions/ in a new browser tab. Check "Developer mode" and you will see a link to the background page beneath the notifier. Click on the link to have the console opened. Now switch to the network tab and see what you get after running the manual check. Take an screenshot and share it here.

**Comment by bob603** [comment] 2016-02-27 13:12
I finally got GN working a couple of days ago in Firefox. I'm pretty sure
it had to do with accepting to save the master account in gmail. Now I've
been using this program for quite a while, but following the written
instructions, it was my understanding that I was not to save passwords. I
mixed up saving the account with saving passwords I guess. Just a
suggestion. Why not create a real simple, quick video to explain how to
install and set up multiple accounts? You might end up finding more users.

On Sat, Feb 27, 2016 at 6:01 AM, InBasic <notifications@github.com> wrote:

> In Chrome debugging is simpler. Open chrome://extensions/ in a new browser
> tab. Check "Developer mode" and you will see a link to the background page
> beneath the notifier. Click on the link to have the console opened. Now
> switch to the network tab and see what you get after running the manual
> check. Take an screenshot and share it here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inbasic/ignotifier/issues/390#issuecomment-189618481>.
>



-- 
~~~~~~~~~~~~~~~~~
robgrant65@gmail.com
~~~~~~~~~~~~~~~~~

**Comment by inbasic** [comment] 2016-02-27 14:07
>  it was my understanding that I was not to save passwords

You are not providing passwords to the GN, but still you need to be logged-in into all your accounts for the notifier to be able to fetch unread emails. Just to clarify this, you don't need to ask your browser to remember passwords, but you need to ask your browser to save the current session.

> Why not create a real simple, quick video to explain how to install and set up multiple accounts? 

Well, if you are interested please do so. You can either write a user-friendly instruction as a blog post and post it on blog.add0n.com or make a short video tutorial which will be inserted in the FAQ page.

p.s: please close all the related bug reports if the problem is resolved.

**Closed by inbasic** 2016-02-27 14:07 UTC
