### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by wiseguy711** [inbasic/ignotifier#618] opened 2023-11-15 19:14 UTC
As of 11/13/2023 you cannot delete emails in the pop-up or read the email. I have to disable it and go directly to gmail to read my messages. It worked great for a long time abut now it is broken.

**Comment by minhpq331** [comment] 2023-11-16 02:21
same here

**Comment by wiseguy711** [comment] 2023-11-16 03:12
It worked fine until the Microsoft big update this week on Windows. I doubt
they ever fix it anymore too. I even tried other ones and none of them work
either.  I had it for years and I miss it already hahahaha Take care.  I
have a computer repair service I called, and they took it over and said it
is not fixable until they do something about it. They need to make it
compatible to the updates we got too.

**Comment by minhpq331** [comment] 2023-11-16 03:19
I have to uninstall this firefox ext and install another one and that works.

**Comment by wiseguy711** [comment] 2023-11-16 03:22
Ok, sounds good. My wife uses Google Chrome and her email notifier for that
works OK.  They use different one..

**Comment by inbasic** [comment] 2023-11-16 04:56
Can you open basic views in browser tabs?
https://mail.google.com/mail/u/0/h/
https://mail.google.com/mail/u/1/h/
https://mail.google.com/mail/u/2/h/

**Comment by iSupremacy** [comment] 2023-11-16 04:56
same same same same same same

**Comment by wiseguy711** [comment] 2023-11-16 05:19
Tried it and no luck. I have a computer repair service, and they tried all
and everything and said on their end they have to make changes to the
software which I doubt they will. You can`t contact them unless they read a
bunch complaining. Thanks for your advice but nothing. I even hated to as I
have lots of stuff add-ons and owned refreshed by them, it still did not
work. The codes are all outdated. they could fix it if they knew.. I can
still get into Gmail, so I will do that with the add-on just more work
that. They even tried to install a few others there and none worked also.
Thanks anyway

**Comment by rolandixor** [comment] 2023-11-16 13:15
Confirmed (not that this helps). It's not even showing me how many emails I have (in Firefox) after reinstalling. I think the addon is broken in the latest update.

**Comment by Shadowpheonix** [comment] 2023-11-16 21:51
Opening the basic view for each of my accounts and continuing past the warning about it being discontinued in January 2024 resolved the issue for me, although I expect it will only be a temporary solution.

**Comment by iSupremacy** [comment] 2023-11-16 21:54
Interesting, thanks for the info. Only reason I needed/starting using is because the native windows mail app is shit and doesn't send instant notifications in the background.

**Comment by wiseguy711** [comment] 2023-11-16 22:09
I still get the email alert and the count, but nothing really works except
tom take you to email and read what it says.  I tried many others, and they
don`t work either. I searched for a replacement, but there are few that
work if at all.  I just use it and open it to delete them. You would think
they could fix the codes that would make it workable, but they don`t.  Take
care

**Comment by JohnnyTMD** [comment] 2023-11-17 08:51
Same issue here, it notifies about new emails, but it's not loading the email body, also can't mark them as read.

**Comment by Shahius** [comment] 2023-11-17 13:56
Same here.

**Comment by peeter22** [comment] 2023-11-17 14:08
> Google is retiring the basic view in January 2024 and I think they're migrating accounts to force the standard view and I think hte extension is dependent on that and the Atom feed. I've been able to go to https://mail.google.com/mail/u/0/h/ and skip it for now and log back in for 2 of my accounts, but worried it will fail come January.

I have tried this method. The extension at least displays the masse body but I am not able to delete or mark it as read. :(

**Comment by wiseguy711** [comment] 2023-11-17 16:08
I use the built-in one in Firefox and still see the counts in the add-on
that don`t work. It sure seems funny they cannot fix the add-on to work
with this. For years, it was OK. I tried other ones, and they won`t work
either. I sent them a letter when it first broke, and they wrote saying it
was being retired and will no longer work other than show the number of
emails. It was due to security reason. Just have to get use to going to
email all the time physically to read them. Take care..

**Comment by kjaerlige** [comment] 2023-11-17 21:46
Same here
@inbasic really hope there's gonna be some workaround or fix, I really like this extension

**Comment by wiseguy711** [comment] 2023-11-17 22:01
Too bad as now I used it for years. I still use it no matter what as I am
just used to it and just have to go through a few other motions to receive
and get to my email. Take care..

**Comment by inbasic** [comment] 2023-11-18 12:29
I am pushing a new update

**Comment by wiseguy711** [comment] 2023-11-18 16:53
I hope it can be updated. It surely is a shame after using it for so long..
That extensions icon also in the Firefox toolbar I wish it could be
removed. All or  any add-on goes to that icon, and you work it from there
but not the email notifier. hahaha Thanks and have a nice holiday..

**Comment by wiseguy711** [comment] 2023-11-20 17:15
I sure hope so....

**Comment by Exathil** [comment] 2023-11-20 20:23
I love the extension, so I am waiting patiently for the fix. Good it is not abandoned <3

**Comment by inbasic** [comment] 2023-11-21 04:51
version 1.1.1 is released on Chrome Webstore. Should have fixed the issue
https://chrome.google.com/webstore/detail/notifier-for-gmail/dcjichoefijpinlfnjghokpkojhlhkgl

**Comment by Avrution** [comment] 2023-11-21 05:55
> version 1.1.1 is released on Chrome Webstore. Should have fixed the issue https://chrome.google.com/webstore/detail/notifier-for-gmail/dcjichoefijpinlfnjghokpkojhlhkgl

Is the change planned for Firefox as well?  Thanks!

**Comment by inbasic** [comment] 2023-11-21 07:20
@Avrution already submitted. It is still on review.

**Comment by s0urcelab** [comment] 2023-11-21 11:32
> version 1.1.1 is released on Chrome Webstore. Should have fixed the issue https://chrome.google.com/webstore/detail/notifier-for-gmail/dcjichoefijpinlfnjghokpkojhlhkgl

Can you update Edge version as well?

**Comment by inbasic** [comment] 2023-11-21 12:02
@s0urcelab same as Firefox, it is still on the review queue

**Comment by jaymeayres** [comment] 2023-11-21 12:19
Same here in Firefox 119.0.1  =(

**Comment by Exathil** [comment] 2023-11-21 12:22
@inbasic Is the Opera fix released? Should I reinstall the extension?

**Comment by HitchEdits** [comment] 2023-11-21 21:51
As of today it seems like it sometimes **fully** breaks (I have a blank email notification? Sometimes an invisible one?). The ones that do still work aren't able to be deleted through the extension however.

**Comment by TonitoDux** [comment] 2023-11-22 06:21
> As of today it seems like it sometimes **fully** breaks (I have a blank email notification? Sometimes an invisible one?). The ones that do still work aren't able to be deleted through the extension however.

I have the same problem. I see the subject of the e-mail but not the body.

**Comment by jtveg** [comment] 2023-11-22 10:14
Version update today **ver 1.1.2** (chrome) has resolved the issues. The extension should auto update itself.

**Comment by TonitoDux** [comment] 2023-11-22 10:28
> Version update today **ver 1.1.2** (chrome) has resolved the issues. The extension should auto update itself.

Hopefully FF gets an update as well...fast.

**Comment by Avrution** [comment] 2023-11-22 15:44
FF update is up.  Email is back to working, but at least for me it seems audio alerts no longer play.  The ability to refresh the email check is also gone.

**Comment by Imold** [comment] 2023-11-22 17:22
> FF update is up. Email is back to working, but at least for me it seems audio alerts no longer play.

Do you have Autoplay disabled? If so see [#598](https://github.com/inbasic/ignotifier/issues/598#issuecomment-1300988972) for solution.

**Comment by Avrution** [comment] 2023-11-22 18:03
> > FF update is up. Email is back to working, but at least for me it seems audio alerts no longer play.
> 
> Do you have Autoplay disabled? If so see [#598](https://github.com/inbasic/ignotifier/issues/598#issuecomment-1300988972) for solution.

No, not the problem.  I run waterfox, so the new extension might not work with older ESR releases.

**Comment by IsletsOfLangerhans** [comment] 2023-11-22 18:28
Same.  Working fine in current release Firefox, does not work in Waterfox Classic.

**Comment by Avrution** [comment] 2023-11-22 18:30
> Same. Working fine in current release Firefox, does not work in Waterfox Classic.

I'm running G5, which is based on Firefox 102 - so it at least doesn't work with something that far back either.

**Comment by Imold** [comment] 2023-11-22 18:51
> > Same. Working fine in current release Firefox, does not work in Waterfox Classic.
> 
> I'm running G5, which is based on Firefox 102 - so it at least doesn't work with something that far back either.

G5 is out of date, you should update it. The current version is G6.0.6 which is based on Firefox 115.  It works on Waterfox G6 but the toolbar button context menu items are missing.

**Comment by ozzyjr** [comment] 2023-11-22 19:06
V2 is working again in Firefox Nightly 122.0a1 (2023-11-22).

V3 doesn't work yet.

**Comment by Avrution** [comment] 2023-11-22 19:09
> G5 is out of date, you should update it. The current version is G6.0.6 which is based on Firefox 115. It works on Waterfox G6.

No desire to move to G6 at this time.  If nothing else, I'll keep using the old addon until support ends.

**Comment by frshhh** [comment] 2023-11-22 19:24
Using Firefox 120.0 and Notifier 1.1.1, Still cant see email contents, just subject.

Also, it doesn't "remember" my gmail addresses after I restart firefox. I have to manually log into each of them (I use 3).

I _CAN_ mark emails as read from the notifier though.

**Comment by ozzyjr** [comment] 2023-11-22 19:29
> Using Firefox 120.0 and Notifier 1.1.1, Still cant see email contents, just the subject line.
> 
> Also, it doesn't "remember" my gmail addresses after I restart firefox. I have to manually log into each of them (I use 3) each time I start firefox.
> 
> I _CAN_ mark emails as read from the notifier though.

I have noticed that my Google accounts have been logging out constantly. It makes sense to be the extension doing this...

**Comment by Levitskyi-M** [comment] 2023-11-22 21:08
The new version 1.1.2, unfortunately, does not work in Opera 95 (the latest version for Win 7 and 8). The text of the email is displayed (thanks), you can go to the inbox, but it is not possible to delete or mark the email as read.

**Comment by Imold** [comment] 2023-11-22 21:46
> The new version 1.1.2, unfortunately, does not work in Opera 95 (the latest version for Win 7 and 8). The text of the email is displayed (thanks), you can go to the inbox, but it is not possible to delete or mark the email as read.

I'm assuming you are using Win 7 or 8 and that's why you're using an out of date browser. If I'm wrong then just update to the latest version of Opera. If you are using Win 7 or 8, then unless you can reproduce the problem on a supported browser on a supported OS it's going to be dismissed as "WON'T FIX".

 If you really are using Win 7 or 8, Please tell me you at least don't have anything important on there.

**Comment by kswartz26** [comment] 2023-11-23 00:33
Just sent a donation in appreciation for keeping this going in spite of Google's constant changes and desupport of alternative interfaces. Thank you!

**Comment by inbasic** [comment] 2023-11-23 05:52
1.1.2 is submittd to Firefox. It will fix compatibility with WaterFox Classic. Also the logout issue.

**Comment by inbasic** [comment] 2023-11-23 05:56
@Levitskyi-M 
> The new version 1.1.2, unfortunately, does not work in Opera 95

Try using the Firefox version on developer mode (v1.1.2). The Chrome version is based on manifest v3 and requires offscreen support (Chrome 116)

@ozzyjr 

> I have noticed that my Google accounts have been logging out constantly. It makes sense to be the extension doing this...

Nope! This extension only fetches feeds and checks the feed outputs. It cannot cause Gmail to logout

**Comment by ozzyjr** [comment] 2023-11-23 12:27
@inbasic 

And will V3 (Developer Edition) receive updates?
I installed it to test, and it is not working on Firefox Nightly and Developer Edition. Both Updated.

**Comment by jaymeayres** [comment] 2023-11-23 13:09
Work here on FF 120.0!! 
\o/ \o/ \o/

**Comment by RunninglVlan** [comment] 2023-11-24 17:21
@Exathil, as there was no comment from developer about Opera version, I got tired of waiting, removed Opera extension and installed the one from Chrome store.

**Comment by inbasic** [comment] 2023-11-25 11:53
> will V3 (Developer Edition) receive updates?

Since the classic version is migrated to manifest v3 (thanks to offscreen API), I might discontinue the "dev" edition. I am not sure yet.

> Still not working at Opera.

Have you tried the Chrome version? I've already submitted the Opera version, but it is very unlikely it will get reviewed.

**Comment by KarlSpackler3131** [comment] 2023-11-25 16:39
> Can you open basic views in browser tabs? https://mail.google.com/mail/u/0/h/ https://mail.google.com/mail/u/1/h/ https://mail.google.com/mail/u/2/h/

clicking through these links opened the gmail accounts, and allowed the notifier to mark as read, archive, and such. problem now is no right-click context menu in the toolbar, just the firefox default, so no refresh, account list, etc.  thanks.

**Comment by MoreSparrows** [comment] 2023-11-26 21:48
I also have the "no right-click context menu" issue in FF. In addition, I can get the extension to track multiple accounts by using the links ( https://mail.google.com/mail/u/0/h/ etc). However, I have to repeat this process every time I open FF. These problems all started within the past week.

Also, just want to say that I always loved the extension & I've gotten lots of great use out of it for many years.

**Comment by Exathil** [comment] 2023-11-26 23:42
> Have you tried the Chrome version? I've already submitted the Opera version, but it is very unlikely it will get reviewed.

Who is responsible for review? You are saying it will never be reviewed? I did not try from Chrome Store yet..

**Comment by inbasic** [comment] 2023-11-28 07:12
Please open a new bug report if you still have issue on 1.1.3 release.

**Closed by inbasic** 2023-11-28 07:12 UTC
