### ISSUE TITLE
Incompatible with Firefox Quantum / current beta 57.0b4

### ISSUE THREAD

**Issue by kjaerlige** [inbasic/ignotifier#474] opened 2017-09-29 18:06 UTC
As many others, currently incompatible with FF version 57 and up. Labelled as the "legacy" extension.

https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

**Comment by goetzc** [comment] 2017-09-30 16:33
Duplicate of issue #460.

**Comment by inbasic** [comment] 2017-10-11 14:57
See #460

**Closed by inbasic** 2017-10-11 14:57 UTC
