### ISSUE TITLE
No Menu Items 

### ISSUE THREAD

**Issue by Taurean75** [inbasic/ignotifier#377] opened 2016-01-01 18:25 UTC
![gmail](https://cloud.githubusercontent.com/assets/8365855/12071734/660eb38e-b070-11e5-8003-0b56c39387bd.jpg) 
![options](https://cloud.githubusercontent.com/assets/8365855/12071779/0cbf7fae-b073-11e5-9f9b-5b1a49e65d90.jpg)

Instead of menu items, it's displaying "label". The options page is not showing any option labels.

v0.58 works fine, though.

Happy New Year!

**Comment by ItsLifeJim** [comment] 2016-01-02 09:04
I'm getting this problem too on v0.60.  My Windows notifications no longer come with content in the popup - just basic text that I have GMail.  I've running Firefox 43.0.3 on Windows 7.

**Comment by inbasic** [comment] 2016-01-02 09:23
Do a restart and see if the problem is resolved or not

**Comment by ItsLifeJim** [comment] 2016-01-02 10:58
A restart didn't help.

**Comment by Taurean75** [comment] 2016-01-02 16:50
I'm using Windows 10 with Firefox 43.0.3 x64.

**Comment by inbasic** [comment] 2016-01-03 06:23
For some reason the locale manager cannot initiate the proper locale. So are you guys using the English locale?

To get more info please follow these steps:
1. Open error console (ctrl + shift + j)
2. Clear the console window
3. Now go to addons page and disable and re-enable the notifier

Is there any new error appears on the console?

**Comment by ItsLifeJim** [comment] 2016-01-03 07:33
On v0.60 I get the following lines:

Disable
----------
Could not read chrome manifest 'file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/chrome.manifest'.
1451805757402	Services.Metrics.Provider.org.mozilla.addons	WARN	Add-on type without field: dictionary
1451805757403	Services.Metrics.Provider.org.mozilla.addons	WARN	Add-on type without field: locale

Enable
---------
1451805790319	Services.Metrics.Provider.org.mozilla.addons	WARN	Add-on type without field: dictionary
1451805790319	Services.Metrics.Provider.org.mozilla.addons	WARN	Add-on type without field: locale

I also get something very similar when disabling/enabling v0.58

**Comment by ItsLifeJim** [comment] 2016-01-03 07:44
PS. I'm currently using en-US. I tried switching to en-GB, but that makes no difference.

**Comment by inbasic** [comment] 2016-01-03 09:43
I just checked the 0.60 on x64 and it works just fine. I am not sure why the extension cannot get the localized strings in your machine.

> I tried switching to en-GB, but that makes no difference.

Have you changed the locale using an extension?

**Comment by ItsLifeJim** [comment] 2016-01-03 10:56
Creating a new firefox profile with only gmail-notifiier seems to fix the problem; however, running my current profile with all other add-ons disabled continues to fail. 

I can't remember running a locale-switcher in the past, but I've had my firefox profile for years so can't say I haven't.

**Comment by inbasic** [comment] 2016-01-03 12:53
@Taurean75 can you also confirm @ItsLifeJim new profile fix?

**Comment by inbasic** [comment] 2016-01-03 12:54
@ItsLifeJim moving your existing extensions to a new profile is pretty simple. Just setup Firefox Sync on your old profile. It will migrate all your extensions and settings to the new profile if you login into your account in the new profile as well.

**Comment by ItsLifeJim** [comment] 2016-01-03 13:20
I tried the profile sync you suggest, but the net result is the problem is copied over to the new profile :-(  I suspect this is preferences being copied across.  

The add-ons I use are:
Adblock Plus
Disconnect
Download Status Bar
Fast Translation
FireFTP
Gmail Notifier (restartless)
Open Bookmarks in New Tab
Tabs on Bottom
Vacuum Places Improved

**Comment by Taurean75** [comment] 2016-01-03 19:00
Recreating the "pref.js" file resolved the problem.

**Comment by UK992** [comment] 2016-01-07 14:17
Recreating "pref.js" is not a solution, after adding back some necessary prefs via sync, strings disappear again.

**Comment by Taurean75** [comment] 2016-01-07 17:24
Don't sync it; start with default settings.

**Comment by ItsLifeJim** [comment] 2016-01-07 17:51
I'm very happy to help debug the locale the problem in v0.6, but less than happy to reset my preferences.  Sticking on v0.58 is my only realistic choice as I've a lot of preferences built up over time and can't stomach the idea of manually reapplying plugin preferences again - not only for my main profile, but for the four other devices that sync with it.

**Comment by UK992** [comment] 2016-01-07 18:28
@Taurean75 as said this is not a solution, there is too many browser and addons prefs, which i don't want to set them again manual, i have sync for that... 
I'm switching back to v0.5.8 for now, this need to be fixed by the addon.

**Comment by Taurean75** [comment] 2016-01-07 19:31
Well, that fixed it for me. By using the sync feature, you're basically re-introducing what's incompatible with this add-on. It's not an ideal solution of course.

**Comment by inbasic** [comment] 2016-01-08 06:22
Can anybody use a text diff tool to figure-out what pref is causing this? Or if your prefs.js does not have any personal info please send it to me to hopefully regenerate the bug.

**Comment by ItsLifeJim** [comment] 2016-01-08 09:37
Think I've found the problem.  My locale (general.useragent.locale) is "en-US" (default) but the locale you are working with only handles "en".  When I set the above preference to "en" and restart Firefox the options menu in v0.6 works. I suspect you either need to support regional language locales or strip the "en-US" to "en".

**Comment by ItsLifeJim** [comment] 2016-01-08 10:16
As a test, I hacked the v0.6 xpi file, copying en.properties to en-US.properties and restarted firefox (xpinstall.signatures.required had to be tweaked).  This seems to work fine :-)

**Comment by inbasic** [comment] 2016-01-10 06:22
@ItsLifeJim that's weird. "en" locale should work just fine when `general.useragent.locale` is set to en-US

> Actually, every language that's not different for different regions should go with the ISO 639.1/.2 (2-letter/3-letter) language code alone ("de", "eo", "pl", "cs", etc.), while all where the region does matter should include it (2-letter uppercased ISO 3166 code; locale strings look like those we have used until now: "es-ES", "es-AR", "pt-PT", "en-US").

https://wiki.mozilla.org/L10n:Locale_Codes

My `general.useragent.locale` is also on en-US and I don't see this problem. Btw, the extension was also on "en" on version 0.5.8 

Guys can you try @ItsLifeJim solution and report back?

**Comment by twu2** [comment] 2016-01-11 09:14
I think I found why we have this issue and how to fix it...

if you've "intl.accept_languages" in your prefs.js, and no 'en' in this setting, you'll get this issue in version 0.6.0 (work fine in 0.5.8)
remove this setting or add 'en' to this will fix this issue (that's why a new prefs.js will work)

**Comment by ItsLifeJim** [comment] 2016-01-11 16:28
The int.accept_languages tweak works for me.  However, lots of other internationalized plugins don't require this, so my preference is for this plugin to follow that lead - either determine base language or provide regional locale files.  For now, the tweak is good enough for me to upgrade to v0.60.

**Comment by UK992** [comment] 2016-01-11 17:31
I have `intl.accept_languages;sl`, and when i add `en`, localization work again.
When i change en.properties to en-US.properties, also work with `sl` only.

**Comment by inbasic** [comment] 2016-01-12 07:30
I updated the compiler to generate both `en` and `en-US` locale files. Please confirm the fix on:
https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true

**Closed** 2016-01-12 08:00 UTC

**Comment by inbasic** [comment] 2016-01-12 08:04
Version 0.6.1 is now submitted to AMO,
https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/versions

**Comment by ItsLifeJim** [comment] 2016-01-12 08:09
The compiler fix works for me.  Thanks for fixing :-)

**Comment by inbasic** [comment] 2016-01-12 08:11
@ItsLifeJim thanks for the confirmation. Have you also tried the submitted version? 
https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/versions/
