### ISSUE TITLE
Show a warning when deleting a chain of letters

### ISSUE THREAD

**Issue by justanotheranonymoususer** [inbasic/ignotifier#343] opened 2015-07-30 20:21 UTC
Please, PLEASE, add a warning when deleting a letter which is in fact a chain of letters. I keep removing important letters I didn't intend to remove because of this misfeature.

**Comment by inbasic** [comment] 2015-08-01 07:32
Well, the notifier does not have access to this info. Actually Gmail feed does not provide these sort of info about emails. Anyhow, the current version of notifier displays all the quoted text in email which can somehow be used to define if an email is actually a thread

Duplicate of https://github.com/inbasic/ignotifier/issues/227

**Closed by inbasic** 2015-08-01 07:32 UTC

**Comment by justanotheranonymoususer** [comment] 2015-08-01 11:55
@inbasic, 

I have looked at it a bit. Seems like when removing a message, you are sending the "tr" command to Gmail, which removes the whole thread.
But Gmail has an option to remove only a single message. Screenshot:

![2015-08-01 14_51_44-asdasd - mmm maltsev gmail com - gmail](https://cloud.githubusercontent.com/assets/5781692/9021758/dd4e1930-385c-11e5-9c49-fd64b7eeaecd.png)

From looking at fiddler, this command is "dm" (for delete message, probably), and the URL looks like this:
```
https://mail.google.com/mail/u/0/?ui=2&ik=XXX&rid=XXX&at=XXX&view=up&act=dm&_reqid=XXX&pcd=1&mb=0&rt=j&search=inbox
```

with post body:
```
m=XXX&
```

(identifiers replaced with XXX)

Could you use this command to remove a single message instead of the whole chain?

**Comment by inbasic** [comment] 2015-08-05 09:41
Doesn't seem like we have all the required identifiers mainly I am not sure what `rid and `_reqid`. Have you tried using it in Notifier?

**Comment by justanotheranonymoususer** [comment] 2015-08-05 10:22
No, I haven't tried it. I assumed that you, as the author of the add-on, will know what to do with it :)
