### ISSUE TITLE
Alerts for single email addresses?

### ISSUE THREAD

**Issue by Buttons01** [inbasic/ignotifier#509] opened 2018-04-11 00:17 UTC
Hi, apologies if I've missed something. I need desktop alerts for emails from one email address alone. Just one. Can I do this with notifier?
Thanks
Daina

**Comment by Buttons01** [comment] 2018-04-11 00:38
Actually don't worry. I've found checker plus and figured that out. But thank you. Your product would be great if I needed more than one email highlighted.

**Comment by inbasic** [comment] 2018-04-28 12:29
duplicate of https://github.com/inbasic/ignotifier/issues/510

**Closed by inbasic** 2018-04-28 12:29 UTC
